#!/bin/bash

# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

### This is a protoc wrapper for tez, which can dinamically call protoc from a downloaded protobuf.

if [ -n "$ZSH_VERSION" ]; then
   SCRIPT_DIR="${0:a:h}"
else
   SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
fi

if test -f "$SCRIPT_DIR/protobuf/bin/protoc"; then
    "$SCRIPT_DIR/protobuf/bin/protoc" "$@"
else
    protoc "$@"
fi
exit $?
